name: nexara_cart
description: "E-Commerce app built in flutter using GetX."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  flutter_cart: ^0.0.9
  get_storage: ^2.1.1
  flutter_login: ^5.0.0
  webview_flutter: ^4.8.0
  flutter_stripe: ^10.2.0
  razorpay_flutter: ^1.3.7
  onesignal_flutter: ^5.2.1
  cupertino_icons: ^1.0.6
  email_validator: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#B9B9AD"
  adaptive_icon_foreground: "assets/images/logo_circle.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#B9B9AD"
  image: "assets/images/splash_logo.png"

  android_12:
    color: "#B9B9AD"
    icon_background_color: "#B9B9AD"
    image: "assets/images/splash_logo.png"